services:
  database:
    image: mysql:9.1.0
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=fundmetrics
      - MYSQL_USER=champdecay
      - MYSQL_PASSWORD=champdecay
    ports:
      - 3307:3306
    volumes:
      - mysql_data:/var/lib/mysql 
  # redis:
  #   image: redis:latest
  #   container_name: redis-cache
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis-data:/data
  server:
    build:
      context: .
    ports:
      - 8080:8080
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - DB_HOST=database
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - database
      # - redis
volumes:
  mysql_data:
    driver: local
  # redis-data: