services:
  database:
    image: postgres:17
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports: 
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgressql/data 
  redis:
    image: redis:latest
    container_name: redis-cache
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data       
  server:
    build:
      context: .
    ports:
      - 8080:8080
    volumes:
      - .:/app
      - /app/node_modules
    environment: 
      - DB_HOST=database    
      - DB_USER=postgres    
      - DB_PASSWORD=postgres    
      - DB_NAME=postgres   
      - REDIS_HOST=redis
      - REDIS_PORT=6379 
    depends_on:
      - database
      - redis
volumes:
  postgres-data:
  redis-data: